# Generated by Django 2.0.4 on 2018-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180308_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='assay_component_endpoint_desc',
            field=models.CharField(max_length=500),
        ),
    ]
