# Generated by Django 2.0.4 on 2018-04-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180410_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='chemicals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DSSTox_Substance_Id', models.CharField(max_length=50)),
                ('DSSTox_Structure_Id', models.CharField(max_length=50)),
                ('DSSTox_QC_Level', models.CharField(max_length=50)),
                ('Substance_Name', models.CharField(max_length=50)),
                ('Substance_CASRN', models.CharField(max_length=50)),
                ('Substance_Type', models.CharField(max_length=50)),
                ('Substance_Note', models.CharField(max_length=50)),
                ('Structure_SMILES', models.CharField(max_length=50)),
                ('Structure_InChI', models.CharField(max_length=50)),
                ('Structure_Formula', models.CharField(max_length=50)),
                ('Structure_MolWt', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='experiment',
            name='assay_component_endpoint_desc',
            field=models.CharField(max_length=255),
        ),
    ]
