# Generated by Django 2.0.4 on 2018-04-10 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180410_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='Structure_InChIKey',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='Structure_InChI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='Structure_SMILES',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='Substance_Name',
            field=models.CharField(max_length=255),
        ),
    ]
