# Generated by Django 2.0.4 on 2018-04-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180410_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toxicity',
        ),
    ]
