# Generated by Django 2.0.4 on 2018-04-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_toxicity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toxicity',
        ),
    ]
